In [1]:
import numpy as np

This way we can create a numpy array where the first arguement denotes the array and the second one denotes the size limit of the data inputed inside that array.

In [2]:
myarr=np.array([[1,2,378745,4,5]],np.int32)                       # increating a 2d array here

In [3]:
myarr[0]

array([     1,      2, 378745,      4,      5])

In [4]:
myarr[0,1]

2

In [5]:
myarr.shape

(1, 5)

In [6]:
myarr.dtype

dtype('int32')

In [7]:
np.array({32,23,45})

array({32, 45, 23}, dtype=object)

In [8]:
zeroes=np.zeros((2,5))

In [9]:
zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
zeroes.shape

(2, 5)

## arange

`arange(start_point, stop,point, difference-between-values)`

In [11]:
arange=np.arange(10,2,3)       

In [12]:
arange

array([], dtype=int32)

## linspace 
`linspace(start_point, end_point, no_of_elements)`

In [13]:
lspace=np.linspace(1,5,10)

In [14]:
lspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

## empty 
will return an empty array of the defined size

In [15]:
empty_array=np.empty((4,6))

In [16]:
empty_array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# empty_like

In [17]:
emp_like=np.empty_like(lspace)

In [18]:
emp_like

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

## Identity
        >returns an identity matrix as per the input no.

In [19]:
ide=np.identity(10)

In [20]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [21]:
ide.shape

(10, 10)

In [22]:
ide.dtype

dtype('float64')

## reshape
>to re

In [23]:
arr=np.arange(99)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [25]:
arr.reshape(3,33)  
# here arr is not getting updated for that we must reinitiailize it like this
# arr=arr.reshape(division,elements to put in each division)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [27]:
arr=arr.reshape(3,33)

In [28]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [29]:
# to reshape the array into it's actual form we must:-
arr=arr.ravel()

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

# NUMPY AXIS

In [31]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [32]:
arr=np.array(x)

In [33]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [34]:
arr.sum(axis=0) # will sum up all the elements lying in the vertical direction path

array([12,  8,  9])

In [35]:
arr.sum(axis=1) # will sum up all the elements lying in the horizontal direction path

array([ 6, 15,  8])

In [36]:
arr.T      #will do the tranpose of the original matrix

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [37]:
for item in arr.flat:      # arr.flat will reshape the nd array to straight chain.
    print(item)

1
2
3
4
5
6
7
1
0


In [38]:
arr.ndim             # returns dimension of the arr

2

In [39]:
arr.size            # returns the no of elements present in the arr

9

In [40]:
arr.nbytes          #returns the no of bytes consumed for the array creation

36

In [41]:
one=np.array([4,85,96,415,1,2])

In [42]:
one.argmax()     # returns maximum element index   -->RUN AS A METHOD 

3

In [43]:
one.argmin()     # returns minimum element index   -->RUN AS A METHOD 

4

In [44]:
one.argsort()    # returns the sequence of indices to have in order to sort the array

array([4, 5, 0, 1, 2, 3], dtype=int64)

In [45]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [46]:
arr.argmin()     # first straights the 2d array and then returns the index of the minimum element

8

In [47]:
arr.argmax()     # first straights the 2d array and then returns the index of the maximum element

6

In [48]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [49]:
arr.argmax(axis=0)  # returns the indices of the maximum element in the vertical columns

array([2, 1, 1], dtype=int64)

In [50]:
arr.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [51]:
arr.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [52]:
arr.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [53]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

## Adding two numpy arrays

In [54]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [55]:
arr2=np.array([[-1, 2, 3],
       [4, -5, -6],
       [7, 1, 0]])

In [56]:
arr+arr2       # adds the respective elements in sequence

array([[ 0,  4,  6],
       [ 8,  0,  0],
       [14,  2,  0]])

In [57]:
arr*arr2

array([[ -1,   4,   9],
       [ 16, -25, -36],
       [ 49,   1,   0]])

In [58]:
np.sqrt(arr)     #Gives the square root of all the elements in the lis

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [59]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [60]:
arr.sum()

29

In [61]:
arr.max()

7

In [62]:
arr.min()

0

In [63]:
np.where(arr>5) # returns the tuple of the arrays where element >5 

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [64]:
np.count_nonzero(arr)

8

In [65]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [66]:
np.nonzero(arr)      #returns the tuple of the coordinates where values are nonzero

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [67]:
arr[1,1]=0
arr[1,2]=0  

In [68]:
np.nonzero(arr)

(array([0, 0, 0, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 0, 1], dtype=int64))

# Numpy takes less space to store itself

In [69]:
py_ar=[1,2,3,4,5,6]

In [70]:
np_ar=np.array(py_ar)

In [71]:
import sys

In [72]:
sys.getsizeof(1) * len(py_ar) # the size of python array is greater than the size of our numpy array

168

In [73]:
np_ar.itemsize*np_ar.size

24

In [74]:
1

1